### ISSUE TITLE
Some missing packages

### ISSUE THREAD

**Issue by productiveme** [gadicc/wmd#1]
Would love to try out your deployment strategy. So far found 2 packages are references from your smart folder: `meteor-extensions` (which I can clone and get working) and `config` which is symlinked to a your local machine, could you perhaps include the code or point me to the repo?

**Comment by productiveme** [comment]
Nevermind... such a generic name, didn't think to check atmosphere first, doh!

**Comment by gadicc** [comment]
Haha, was wondering if I left this as a public repo how long it would take for someone to notice :>  You're welcome to play around, but I should note that this is far from "public" yet.  Despite it being cloneable, I'd appreciate if you didn't mention it anywhere else for now.

Some notes: 1) UI still needs a lot of work.  If you click a button and you think nothing happened, check the 'Logs' link.  2) You still need to manually click the Setup button after creating a new server/app (for now).  2) Mongo deploys not implemented yet.  3) The run Meteor directly was a fail, it consumes too much RAM/CPU.  Looking into some other "innovative" approaches for quicker deploy times (but probably just regular bundle, perhaps with an option to still run Meteor continuously on the control server).  4) This it not reliable even for devel deployments yet (ok, well, maybe semi... we're using it internally but we know it's limitations better).  5) I removed the local deps.

I see you're from CT :)  I'm from there originally, hope to be there for the next Meetup!
